import McqLayout from "../../../layouts/Mcqlayout";

function QuizApp() {
    const quizData = [
        {
            question: "What is artificial intelligence",
            options: [
                "Playing game",
                "Putting intelligence into computer",
                "programming with your own intelligence",
                "Making machine intelligent"
            ],
            answer: "Making machine intelligent",
        },
        {
            question: "LISP was created by :",
            options: [
                "John McCarthy",
                "Marvin Minsky",
                "Alan Turing",
                "Allen Newell and Herbert Simon"
            ],
            answer: "John McCarthy",
        },
        {
            question: "Expert Ease was developed under the direction of",
            options: [
                "Lofti Zadeh",
                "Bill Gates",
                "Donald Michie",
                "Alan Turing"
            ],
            answer: "Donald Michie"
        },
        {
            question: "Strong Artificial Intelligence is",
            options: [
                "study of mental facilities thorugh of use of mental model implemented on a computer",
                "Embodiment of human intellectual capabilities within a computer",
                "Set of computer programs that product output that would be considered to reflect intelligence if it were generated by humans",
                "none of tha above"
            ],
            answer: "Embodiment of human intellectual capabilities within a computer"
        },
        {
            question: "In which of the following situation might a blind search be acceptable",
            options: [
                "Real life situation",
                "Complex game",
                "Blind search algorithm",
                "Small search space"
            ],
            answer: "Small search space"
        }

    ];
    const optionLetters = [ 'A', 'B', 'C', 'D' ];
    return (
        <McqLayout>
            <section id="content-wrapper">
                <div className="quiz-app p-4">
                    <h2 className="  text-blue-700 text-2xl text-center sm:text-xl  xl:text-4xl dark:text-blue">AI History MCQ</h2>
                    { quizData.map( ( questionObj, index ) => (
                        <div className=" space-y-6 py-8 text-base leading-7 " key={ index }>
                            <p className="font-bold">Question :  { questionObj.question }</p>
                            <ul className="space-y-4">
                                { questionObj.options.map( ( option, optionIndex ) => (
                                    <li className="flex items-center" key={ optionIndex }>
                                        <div className=" h-6 w-6 flex-none fill-sky-100 stroke-sky-500 stroke-2 mr-3">
                                            <h1 className="mx-auto font-semibold bg-blue-700 rounded-full text-lg text-white text-center">{ optionLetters[ optionIndex ] }</h1>
                                        </div>
                                        { option }</li>
                                ) ) }
                            </ul>
                            <details className=" open:duration-300">
                                <summary className="px-5 py-3 text-lg cursor-pointer">Answer:</summary>
                                <div className=" px-5 py-3 border border-blue-700 text-sm">
                                    { questionObj.answer }
                                </div>
                            </details>
                        </div>
                    ) ) }
                </div>
            </section>
        </McqLayout>
    );
}

export default QuizApp;